#
# Docker swarm configuration for ubin fabric network.
# This is generated automatically by network-gen.sh.
#

version: "3.2"

services:
   ###############################################
   # Orderer
   ###############################################

   orderer:
      container_name: orderer.example.com
      image: hyperledger/fabric-orderer:x86_64-1.0.1
      environment:
         - ORDERER_GENERAL_LOGLEVEL=debug
         - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
         - ORDERER_GENERAL_GENESISMETHOD=file
         - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
         - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
         - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
         - ORDERER_GENERAL_TLS_ENABLED=false
         - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
         - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
         - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peermasgsgsg/tls/ca.crt, /etc/hyperledger/crypto/peerbofasg2x/tls/ca.crt, /etc/hyperledger/crypto/peerchassgsg/tls/ca.crt, /etc/hyperledger/crypto/peercitisgsg/tls/ca.crt, /etc/hyperledger/crypto/peercsfbsgsx/tls/ca.crt, /etc/hyperledger/crypto/peerdbsssgsg/tls/ca.crt, /etc/hyperledger/crypto/peerhsbcsgsg/tls/ca.crt, /etc/hyperledger/crypto/peermtbcsgsg/tls/ca.crt, /etc/hyperledger/crypto/peerocbcsgsg/tls/ca.crt, /etc/hyperledger/crypto/peerscblsgsg/tls/ca.crt, /etc/hyperledger/crypto/peeruobvsgsg/tls/ca.crt, /etc/hyperledger/crypto/peerxsimsgsg/tls/ca.crt]
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric
      command: orderer
      ports:
         - 7050:7050
      volumes:
         - ./channel-artifacts/:/etc/hyperledger/configtx
         - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/crypto/orderer
         - ./crypto-config/peerOrganizations/masgsgsg.example.com/peers/peer0.masgsgsg.example.com/:/etc/hyperledger/crypto/peermasgsgsg
         - ./crypto-config/peerOrganizations/bofasg2x.example.com/peers/peer0.bofasg2x.example.com/:/etc/hyperledger/crypto/peerbofasg2x
         - ./crypto-config/peerOrganizations/chassgsg.example.com/peers/peer0.chassgsg.example.com/:/etc/hyperledger/crypto/peerchassgsg
         - ./crypto-config/peerOrganizations/citisgsg.example.com/peers/peer0.citisgsg.example.com/:/etc/hyperledger/crypto/peercitisgsg
         - ./crypto-config/peerOrganizations/csfbsgsx.example.com/peers/peer0.csfbsgsx.example.com/:/etc/hyperledger/crypto/peercsfbsgsx
         - ./crypto-config/peerOrganizations/dbsssgsg.example.com/peers/peer0.dbsssgsg.example.com/:/etc/hyperledger/crypto/peerdbsssgsg
         - ./crypto-config/peerOrganizations/hsbcsgsg.example.com/peers/peer0.hsbcsgsg.example.com/:/etc/hyperledger/crypto/peerhsbcsgsg
         - ./crypto-config/peerOrganizations/mtbcsgsg.example.com/peers/peer0.mtbcsgsg.example.com/:/etc/hyperledger/crypto/peermtbcsgsg
         - ./crypto-config/peerOrganizations/ocbcsgsg.example.com/peers/peer0.ocbcsgsg.example.com/:/etc/hyperledger/crypto/peerocbcsgsg
         - ./crypto-config/peerOrganizations/scblsgsg.example.com/peers/peer0.scblsgsg.example.com/:/etc/hyperledger/crypto/peerscblsgsg
         - ./crypto-config/peerOrganizations/uobvsgsg.example.com/peers/peer0.uobvsgsg.example.com/:/etc/hyperledger/crypto/peeruobvsgsg
         - ./crypto-config/peerOrganizations/xsimsgsg.example.com/peers/peer0.xsimsgsg.example.com/:/etc/hyperledger/crypto/peerxsimsgsg
      networks:
         fabric:
            aliases:
               - orderer.example.com
      deploy:
         mode: replicated
         replicas: 1
         restart_policy:
            condition: on-failure
            max_attempts: 1
         placement:
            constraints: [node.role == manager]

   ###############################################
   # MASGSGSG organization
   ###############################################

   ca-masgsgsg:
      container_name: ca.masgsgsg.example.com
      image: hyperledger/fabric-ca:x86_64-1.0.1
      environment:
         - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
         - FABRIC_CA_SERVER_CA_NAME=ca.masgsgsg.example.com
         - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.masgsgsg.example.com-cert.pem
         - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4ec9329a2051a26ad7066268e0121d6b6b40b4573907625febd04847b76bde8a_sk
         - FABRIC_CA_SERVER_TLS_ENABLED=false
         - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.masgsgsg.example.com-cert.pem
         - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4ec9329a2051a26ad7066268e0121d6b6b40b4573907625febd04847b76bde8a_sk
      ports:
         - "7054:7054"
      command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
      volumes:
         - ./crypto-config/peerOrganizations/masgsgsg.example.com/ca:/etc/hyperledger/fabric-ca-server-config
      networks:
         fabric:
            aliases:
               - ca.masgsgsg.example.com
      deploy:
         mode: replicated
         restart_policy:
            condition: on-failure
            max_attempts: 1
         placement:
            constraints: [node.hostname == ntkong-vnpay]

   peer0-masgsgsg:
      container_name: peer0.masgsgsg.example.com
      image: hyperledger/fabric-peer:x86_64-1.0.1
      environment:
         - CORE_LOGGING_PEER=debug
         - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
         - CORE_CHAINCODE_KEEPALIVE=180
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - CORE_PEER_ID=peer0.masgsgsg.example.com
         - CORE_PEER_ADDRESS=peer0.masgsgsg.example.com:7051
         - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ubin_fabric
         - CORE_PEER_LOCALMSPID=masgsgsgMSP
         - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
         - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
         - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-masgsgsg:5984
         - CORE_CHAINCODE_STARTUPTIMEOUT=600s
         - CORE_CHAINCODE_DEPLOYTIMEOUT=600s
         - CORE_PEER_TLS_ENABLED=false
         - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
         - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
         - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: sh -c 'sleep 60; peer node start'
      ports:
         - 7051:7051
         - 7053:7053
      volumes:
         - /var/run/:/host/var/run/
         - ./channel-artifacts/:/etc/hyperledger/configtx
         - ./crypto-config/peerOrganizations/masgsgsg.example.com/peers/peer0.masgsgsg.example.com/:/etc/hyperledger/crypto/peer
         - ./crypto-config/peerOrganizations/masgsgsg.example.com/users:/etc/hyperledger/crypto/msp/users
         - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/:/etc/hyperledger/crypto/orderer
      depends_on:
         - orderer.example.com
         - couchdb-masgsgsg
      networks:
         fabric:
            aliases:
               - peer0.masgsgsg.example.com
      deploy:
         mode: replicated
         restart_policy:
            condition: on-failure
            max_attempts: 1
         placement:
            constraints: [node.hostname == ntkong-vnpay]

   couchdb-masgsgsg:
      container_name: couchdb-masgsgsg
      image: hyperledger/fabric-couchdb:x86_64-1.0.1
      ports:
         - 5984:5984
      environment:
         DB_URL: http://localhost:5984/member_db
      networks:
         fabric:
            aliases:
               - couchdb-masgsgsg
      deploy:
         mode: replicated
         restart_policy:
            condition: on-failure
            max_attempts: 1
         placement:
            constraints: [node.hostname == ntkong-vnpay]

   ###############################################
   # BOFASG2X organization
   ###############################################

   ca-bofasg2x:
      container_name: ca.bofasg2x.example.com
      image: hyperledger/fabric-ca:x86_64-1.0.1
      environment:
         - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
         - FABRIC_CA_SERVER_CA_NAME=ca.bofasg2x.example.com
         - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bofasg2x.example.com-cert.pem
         - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/46213eb308f805eabf56f35fac8d389b49e03a13ede77dfa23ff017b82d0a6e4_sk
         - FABRIC_CA_SERVER_TLS_ENABLED=false
         - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bofasg2x.example.com-cert.pem
         - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/46213eb308f805eabf56f35fac8d389b49e03a13ede77dfa23ff017b82d0a6e4_sk
      ports:
         - "8054:7054"
      command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
      volumes:
         - ./crypto-config/peerOrganizations/bofasg2x.example.com/ca:/etc/hyperledger/fabric-ca-server-config
      networks:
         fabric:
            aliases:
               - ca.bofasg2x.example.com
      deploy:
         mode: replicated
         restart_policy:
            condition: on-failure
            max_attempts: 1
         placement:
            constraints: [node.hostname == ntkong-vnpay]

   peer0-bofasg2x:
      container_name: peer0.bofasg2x.example.com
      image: hyperledger/fabric-peer:x86_64-1.0.1
      environment:
         - CORE_LOGGING_PEER=debug
         - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
         - CORE_CHAINCODE_KEEPALIVE=180
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - CORE_PEER_ID=peer0.bofasg2x.example.com
         - CORE_PEER_ADDRESS=peer0.bofasg2x.example.com:7051
         - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ubin_fabric
         - CORE_PEER_LOCALMSPID=bofasg2xMSP
         - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
         - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
         - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-bofasg2x:5984
         - CORE_CHAINCODE_STARTUPTIMEOUT=600s
         - CORE_CHAINCODE_DEPLOYTIMEOUT=600s
         - CORE_PEER_TLS_ENABLED=false
         - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
         - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
         - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: sh -c 'sleep 60; peer node start'
      ports:
         - 8051:7051
         - 8053:7053
      volumes:
         - /var/run/:/host/var/run/
         - ./channel-artifacts/:/etc/hyperledger/configtx
         - ./crypto-config/peerOrganizations/bofasg2x.example.com/peers/peer0.bofasg2x.example.com/:/etc/hyperledger/crypto/peer
         - ./crypto-config/peerOrganizations/bofasg2x.example.com/users:/etc/hyperledger/crypto/msp/users
         - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/:/etc/hyperledger/crypto/orderer
      depends_on:
         - orderer.example.com
         - couchdb-bofasg2x
      networks:
         fabric:
            aliases:
               - peer0.bofasg2x.example.com
      deploy:
         mode: replicated
         restart_policy:
            condition: on-failure
            max_attempts: 1
         placement:
            constraints: [node.hostname == ntkong-vnpay]

   couchdb-bofasg2x:
      container_name: couchdb-bofasg2x
      image: hyperledger/fabric-couchdb:x86_64-1.0.1
      ports:
         - 6984:5984
      environment:
         DB_URL: http://localhost:5984/member_db
      networks:
         fabric:
            aliases:
               - couchdb-bofasg2x
      deploy:
         mode: replicated
         restart_policy:
            condition: on-failure
            max_attempts: 1
         placement:
            constraints: [node.hostname == ntkong-vnpay]

   ###############################################
   # CHASSGSG organization
   ###############################################

   ca-chassgsg:
      container_name: ca.chassgsg.example.com
      image: hyperledger/fabric-ca:x86_64-1.0.1
      environment:
         - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
         - FABRIC_CA_SERVER_CA_NAME=ca.chassgsg.example.com
         - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.chassgsg.example.com-cert.pem
         - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0121a2f25668426d74af340ae39cd2b576a0d370d61434cc058c69f0e9cdcca1_sk
         - FABRIC_CA_SERVER_TLS_ENABLED=false
         - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.chassgsg.example.com-cert.pem
         - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0121a2f25668426d74af340ae39cd2b576a0d370d61434cc058c69f0e9cdcca1_sk
      ports:
         - "9054:7054"
      command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
      volumes:
         - ./crypto-config/peerOrganizations/chassgsg.example.com/ca:/etc/hyperledger/fabric-ca-server-config
      networks:
         fabric:
            aliases:
               - ca.chassgsg.example.com
      deploy:
         mode: replicated
         restart_policy:
            condition: on-failure
            max_attempts: 1
         placement:
            constraints: [node.hostname == ntkong-vnpay]

   peer0-chassgsg:
      container_name: peer0.chassgsg.example.com
      image: hyperledger/fabric-peer:x86_64-1.0.1
      environment:
         - CORE_LOGGING_PEER=debug
         - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
         - CORE_CHAINCODE_KEEPALIVE=180
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - CORE_PEER_ID=peer0.chassgsg.example.com
         - CORE_PEER_ADDRESS=peer0.chassgsg.example.com:7051
         - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ubin_fabric
         - CORE_PEER_LOCALMSPID=chassgsgMSP
         - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
         - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
         - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-chassgsg:5984
         - CORE_CHAINCODE_STARTUPTIMEOUT=600s
         - CORE_CHAINCODE_DEPLOYTIMEOUT=600s
         - CORE_PEER_TLS_ENABLED=false
         - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
         - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
         - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: sh -c 'sleep 60; peer node start'
      ports:
         - 9051:7051
         - 9053:7053
      volumes:
         - /var/run/:/host/var/run/
         - ./channel-artifacts/:/etc/hyperledger/configtx
         - ./crypto-config/peerOrganizations/chassgsg.example.com/peers/peer0.chassgsg.example.com/:/etc/hyperledger/crypto/peer
         - ./crypto-config/peerOrganizations/chassgsg.example.com/users:/etc/hyperledger/crypto/msp/users
         - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/:/etc/hyperledger/crypto/orderer
      depends_on:
         - orderer.example.com
         - couchdb-chassgsg
      networks:
         fabric:
            aliases:
               - peer0.chassgsg.example.com
      deploy:
         mode: replicated
         restart_policy:
            condition: on-failure
            max_attempts: 1
         placement:
            constraints: [node.hostname == ntkong-vnpay]

   couchdb-chassgsg:
      container_name: couchdb-chassgsg
      image: hyperledger/fabric-couchdb:x86_64-1.0.1
      ports:
         - 7984:5984
      environment:
         DB_URL: http://localhost:5984/member_db
      networks:
         fabric:
            aliases:
               - couchdb-chassgsg
      deploy:
         mode: replicated
         restart_policy:
            condition: on-failure
            max_attempts: 1
         placement:
            constraints: [node.hostname == ntkong-vnpay]

networks:
   fabric:
      driver: overlay
      attachable: true
